# Generated by Django 5.0.7 on 2024-08-01 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='identifiant_forum',
        ),
        migrations.AddField(
            model_name='forum',
            name='identifiant_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='forumapp.category'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
