# Generated by Django 5.0.7 on 2024-09-05 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0004_remove_thread_identifiant_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forumapp.message'),
        ),
    ]
